# Generated by Django 5.2.4 on 2025-07-19 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_remove_news_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='reference',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
