services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: gunicorn roshanNewsProject.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - DOCKER_ENV=true
    depends_on:
      - redis

  celery:
    build:
      context: .
      dockerfile: Dockerfile
    command: celery -A roshanNewsProject worker -l info
    volumes:
      - .:/app
    environment:
      - DOCKER_ENV=true
    depends_on:
      - redis

  celery-beat:
    build:
      context: .
      dockerfile: Dockerfile
    command: celery -A roshanNewsProject beat -l info
    volumes:
      - .:/app
    environment:
      - DOCKER_ENV=true
    depends_on:
      - redis

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  crawler:
    image: mcr.microsoft.com/playwright/python:v1.44.0
    working_dir: /app
    volumes:
      - .:/app
    command: >
      bash -c "pip install -r requirements.txt &&
               playwright install &&
               scrapy crawl zoomit"
    environment:
      - DOCKER_ENV=true
    depends_on:
      - redis

  flower:
    build:
      context: .
      dockerfile: Dockerfile
    command: celery -A roshanNewsProject flower --port=5555
    ports:
      - "5555:5555"
    depends_on:
      - redis
    volumes:
      - .:/app
    environment:
      - DOCKER_ENV=true
